[build]
builder = "RAILPACK"
buildCommand = "npm install --legacy-peer-deps && npm run build:shared && npm run build:frontend"
watchPaths = ["frontend/**", "shared/**"]

[deploy]
numReplicas = 1
startCommand = "npm start --workspace=frontend"
serverless = true
restartPolicyType = "NEVER"
restartPolicyMaxRetries = 0

[deploy.healthcheck]
path = "/"
timeout = 100

[deploy.resources]
cpu = 0.5
memory = 512
